# This is a basic workflow to help you get started with Actions

name: Run Deck

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup deck
        uses: kong/setup-deck@v1
        with: 
          deck-version: "1.8.0"
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run deck deck-sync
        run: deck sync --kong-addr http://44.194.158.130:8001

     
